#ifndef M_NAME_TABLE_H
#define M_NAME_TABLE_H

#include "ultra64.h"
#include "m_collision_bg.h"

typedef struct NameTableOffsetTable {
    s32 type;
    mCoBG_unkStruct2 unk4;
} NameTableOffsetTable;

extern s16 move_obj_profile_table[];
extern s16 actor_profile_table[];
extern s16 props_profile_table[];
extern u8 npc_looks_table[];

s32 mNT_get_itemTableNo(u16 item);
u16 mNT_FishIdx2FishItemNo(s32 idx);
u16 bg_item_fg_sub(u16 item, s16 flag);
u16 bg_item_fg_sub_tree_grow(u16 item, s32 pastDays, s32 checkPlant);
u16 bg_item_fg_sub_dig2take_conv(u16 item);
NameTableOffsetTable* obj_hight_table_item0_nogrow(u16 item);

#define GET_NAME_ITEM_CATEGORY(f) (((f) & 0x0F00) >> 8)
#define GET_NAME_ITEM_TYPE(n) (((n) & 0xF000) >> 12)
#define GET_NAME_ITEM_INDEX(n) ((u16)(n) & 0xFF)

#define EMPTY_NO 0x0000

#define ITM_MONEY_START 0x2100
#define ITM_MONEY_1000 ITM_MONEY_START // 0x2100
#define ITM_MONEY_10000 (ITM_MONEY_1000 + 1) // 0x2101
#define ITM_MONEY_30000 (ITM_MONEY_10000 + 1) // 0x2102
#define ITM_MONEY_100 (ITM_MONEY_30000 + 1) // 0x2103
#define ITM_MONEY_END ITM_MONEY_100 // 0x2103

#define ITM_FOOD_START 0x2800
#define ITM_FOOD_APPLE ITM_FOOD_START
#define ITM_FOOD_CHERRY (ITM_FOOD_APPLE + 1)
#define ITM_FOOD_PEAR (ITM_FOOD_CHERRY + 1)
#define ITM_FOOD_PEACH (ITM_FOOD_PEAR + 1)
#define ITM_FOOD_ORANGE (ITM_FOOD_PEACH + 1)
#define ITM_FOOD_MUSHROOM (ITM_FOOD_ORANGE + 1)
#define ITM_FOOD_CANDY (ITM_FOOD_MUSHROOM + 1)
#define ITM_FOOD_COCONUT (ITM_FOOD_CANDY + 1)
#define ITM_FOOD_END 0x2808

typedef enum {
    /* 0  */ NAME_TYPE_ITEM0,  /* Scenery items */
    /* 1  */ NAME_TYPE_FTR0,   /* Furniture 0 */
    /* 2  */ NAME_TYPE_ITEM1,  /* Obtainable items */
    /* 3  */ NAME_TYPE_FTR1,   /* Furniture 1 */
    /* 4  */ NAME_TYPE_WARP,   /* Loading zones */
    /* 5  */ NAME_TYPE_STRUCT, /* Structures */
    /* 6  */ NAME_TYPE_PAD6,   /* Unused? */
    /* 7  */ NAME_TYPE_PAD7,   /* Unused? */
    /* 8  */ NAME_TYPE_ITEM2,  /* Misc items */
    /* 9  */ NAME_TYPE_ACTOR,  /* Actors */
    /* 10 */ NAME_TYPE_PROPS,  /* Props */
    /* 11 */ NAME_TYPE_PADB,   /* Unused? */
    /* 12 */ NAME_TYPE_PADC,   /* Unused? */
    /* 13 */ NAME_TYPE_SPNPC,  /* Special NPCs */
    /* 14 */ NAME_TYPE_NPC,    /* Villager NPCs */
    /* 15 */ NAME_TYPE_PAD15,  /* Unused? */
    /* 16 */ NAME_TYPE_NUM,
} NAME_TYPE;

typedef enum {
    /* 0  */ ITEM1_CAT_PAPER,
    /* 1  */ ITEM1_CAT_MONEY,
    /* 2  */ ITEM1_CAT_TOOL,
    /* 3  */ ITEM1_CAT_FISH,
    /* 4  */ ITEM1_CAT_CLOTH,
    /* 5  */ ITEM1_CAT_ETC,
    /* 6  */ ITEM1_CAT_CARPET,
    /* 7  */ ITEM1_CAT_WALL,
    /* 8  */ ITEM1_CAT_FRUIT,
    /* 9  */ ITEM1_CAT_PLANT,
    /* 10 */ ITEM1_CAT_MINIDISK,
    /* 11 */ ITEM1_CAT_DUMMY, /* diaries */
    /* 12 */ ITEM1_CAT_TICKET,
    /* 13 */ ITEM1_CAT_INSECT,
    /* 14 */ ITEM1_CAT_HUKUBUKURO,
    /* 15 */ ITEM1_CAT_KABU,
    /* 16 */ ITEM1_CAT_NUM
} ITEM1_CAT;

/* begin environmental/nature objects */
#define ENV_START 0x0800
/* tree */
#define TREE_SAPLING ENV_START
#define TREE_S0 (TREE_SAPLING + 1)
#define TREE_S1 (TREE_S0 + 1)
#define TREE_S2 (TREE_S1 + 1)
#define TREE (TREE_S2 + 1) /* fully grown */
/* apple tree */
#define TREE_APPLE_SAPLING (TREE + 1)
#define TREE_APPLE_S0 (TREE_APPLE_SAPLING + 1)
#define TREE_APPLE_S1 (TREE_APPLE_S0 + 1)
#define TREE_APPLE_S2 (TREE_APPLE_S1 + 1)
#define TREE_APPLE_NOFRUIT_0 (TREE_APPLE_S2 + 1) /* fully grown, no fruit */
#define TREE_APPLE_NOFRUIT_1 (TREE_APPLE_NOFRUIT_0 + 1)
#define TREE_APPLE_NOFRUIT_2 (TREE_APPLE_NOFRUIT_1 + 1)
#define TREE_APPLE_FRUIT (TREE_APPLE_NOFRUIT_2 + 1)
/* orange tree */
#define TREE_ORANGE_SAPLING (TREE_APPLE_FRUIT + 1)
#define TREE_ORANGE_S0 (TREE_ORANGE_SAPLING + 1)
#define TREE_ORANGE_S1 (TREE_ORANGE_S0 + 1)
#define TREE_ORANGE_S2 (TREE_ORANGE_S1 + 1) /* fully grown, no fruit */
#define TREE_ORANGE_NOFRUIT_0 (TREE_ORANGE_S2 + 1)
#define TREE_ORANGE_NOFRUIT_1 (TREE_ORANGE_NOFRUIT_0 + 1)
#define TREE_ORANGE_NOFRUIT_2 (TREE_ORANGE_NOFRUIT_1 + 1)
#define TREE_ORANGE_FRUIT (TREE_ORANGE_NOFRUIT_2 + 1)
/* peach tree */
#define TREE_PEACH_SAPLING (TREE_ORANGE_FRUIT + 1)
#define TREE_PEACH_S0 (TREE_PEACH_SAPLING + 1)
#define TREE_PEACH_S1 (TREE_PEACH_S0 + 1)
#define TREE_PEACH_S2 (TREE_PEACH_S1 + 1)
#define TREE_PEACH_NOFRUIT_0 (TREE_PEACH_S2 + 1) /* fully grown, no fruit */
#define TREE_PEACH_NOFRUIT_1 (TREE_PEACH_NOFRUIT_0 + 1)
#define TREE_PEACH_NOFRUIT_2 (TREE_PEACH_NOFRUIT_1 + 1)
#define TREE_PEACH_FRUIT (TREE_PEACH_NOFRUIT_2 + 1)
/* pear tree */
#define TREE_PEAR_SAPLING (TREE_PEACH_FRUIT + 1)
#define TREE_PEAR_S0 (TREE_PEAR_SAPLING + 1)
#define TREE_PEAR_S1 (TREE_PEAR_S0 + 1)
#define TREE_PEAR_S2 (TREE_PEAR_S1 + 1)
#define TREE_PEAR_NOFRUIT_0 (TREE_PEAR_S2 + 1) /* fully grown, no fruit */
#define TREE_PEAR_NOFRUIT_1 (TREE_PEAR_NOFRUIT_0 + 1)
#define TREE_PEAR_NOFRUIT_2 (TREE_PEAR_NOFRUIT_1 + 1)
#define TREE_PEAR_FRUIT (TREE_PEAR_NOFRUIT_2 + 1)
/* cherry tree */
#define TREE_CHERRY_SAPLING (TREE_PEAR_FRUIT + 1)
#define TREE_CHERRY_S0 (TREE_CHERRY_SAPLING + 1)
#define TREE_CHERRY_S1 (TREE_CHERRY_S0 + 1)
#define TREE_CHERRY_S2 (TREE_CHERRY_S1 + 1)
#define TREE_CHERRY_NOFRUIT_0 (TREE_CHERRY_S2 + 1) /* fully grown, no fruit */
#define TREE_CHERRY_NOFRUIT_1 (TREE_CHERRY_NOFRUIT_0 + 1)
#define TREE_CHERRY_NOFRUIT_2 (TREE_CHERRY_NOFRUIT_1 + 1)
#define TREE_CHERRY_FRUIT (TREE_CHERRY_NOFRUIT_2 + 1)
/* money tree (1,000 Bells) */
#define TREE_1000BELLS_SAPLING (TREE_CHERRY_FRUIT + 1)
#define TREE_1000BELLS_S0 (TREE_1000BELLS_SAPLING + 1)
#define TREE_1000BELLS_S1 (TREE_1000BELLS_S0 + 1)
#define TREE_1000BELLS_S2 (TREE_1000BELLS_S1 + 1)
#define TREE_1000BELLS (TREE_1000BELLS_S2 + 1) /* fully grown w/ bells */
/* money tree (10,000 Bells) */
#define TREE_10000BELLS_SAPLING (TREE_1000BELLS + 1)
#define TREE_10000BELLS_S0 (TREE_10000BELLS_SAPLING + 1)
#define TREE_10000BELLS_S1 (TREE_10000BELLS_S0 + 1)
#define TREE_10000BELLS_S2 (TREE_10000BELLS_S1 + 1)
#define TREE_10000BELLS (TREE_10000BELLS_S2 + 1) /* fully grown w/ bells */
/* money tree (30,000 Bells) */
#define TREE_30000BELLS_SAPLING (TREE_10000BELLS + 1)
#define TREE_30000BELLS_S0 (TREE_30000BELLS_SAPLING + 1)
#define TREE_30000BELLS_S1 (TREE_30000BELLS_S0 + 1)
#define TREE_30000BELLS_S2 (TREE_30000BELLS_S1 + 1)
#define TREE_30000BELLS (TREE_30000BELLS_S2 + 1) /* fully grown w/ bells */
/* flower leaves (unused growth stage) */
#define FLOWER_LEAVES_PANSIES0 (TREE_30000BELLS + 1) /* white */
#define FLOWER_LEAVES_PANSIES1 (FLOWER_LEAVES_PANSIES0 + 1) /* purple */
#define FLOWER_LEAVES_PANSIES2 (FLOWER_LEAVES_PANSIES1 + 1) /* yellow */
#define FLOWER_LEAVES_COSMOS0 (FLOWER_LEAVES_PANSIES2 + 1) /* yellow */
#define FLOWER_LEAVES_COSMOS1 (FLOWER_LEAVES_COSMOS0 + 1) /* purple */
#define FLOWER_LEAVES_COSMOS2 (FLOWER_LEAVES_COSMOS1 + 1) /* blue */
#define FLOWER_LEAVES_TULIP0 (FLOWER_LEAVES_COSMOS2 + 1) /* red */
#define FLOWER_LEAVES_TULIP1 (FLOWER_LEAVES_TULIP0 + 1) /* white */
#define FLOWER_LEAVES_TULIP2 (FLOWER_LEAVES_TULIP1 + 1) /* yellow */
/* flowers */
#define FLOWER_PANSIES0 (FLOWER_LEAVES_TULIP2 + 1) /* white */
#define FLOWER_PANSIES1 (FLOWER_PANSIES0 + 1) /* purple */
#define FLOWER_PANSIES2 (FLOWER_PANSIES1 + 1) /* yellow */
#define FLOWER_COSMOS0 (FLOWER_PANSIES2 + 1) /* yellow */
#define FLOWER_COSMOS1 (FLOWER_COSMOS0 + 1) /* purple */
#define FLOWER_COSMOS2 (FLOWER_COSMOS1 + 1) /* blue */
#define FLOWER_TULIP0 (FLOWER_COSMOS2 + 1) /* red */
#define FLOWER_TULIP1 (FLOWER_TULIP0 + 1) /* white */
#define FLOWER_TULIP2 (FLOWER_TULIP1 + 1) /* yellow */
/* dead sapling */
#define DEAD_SAPLING (FLOWER_TULIP2 + 1)
/* money tree (100 Bells) */
#define TREE_100BELLS_SAPLING (DEAD_SAPLING + 1)
#define TREE_100BELLS_S0 (TREE_100BELLS_SAPLING + 1)
#define TREE_100BELLS_S1 (TREE_100BELLS_S0 + 1)
#define TREE_100BELLS_S2 (TREE_100BELLS_S1 + 1)
#define TREE_100BELLS (TREE_100BELLS_S2 + 1) /* fully grown w/ bells */
/* palm tree */
#define TREE_PALM_SAPLING (TREE_100BELLS + 1)
#define TREE_PALM_S0 (TREE_PALM_SAPLING + 1)
#define TREE_PALM_S1 (TREE_PALM_S0 + 1)
#define TREE_PALM_S2 (TREE_PALM_S1 + 1)
#define TREE_PALM_NOFRUIT_0 (TREE_PALM_S2 + 1) /* fully grown, no fruit */
#define TREE_PALM_NOFRUIT_1 (TREE_PALM_NOFRUIT_0 + 1)
#define TREE_PALM_NOFRUIT_2 (TREE_PALM_NOFRUIT_1 + 1)
#define TREE_PALM_FRUIT (TREE_PALM_NOFRUIT_2 + 1)
#define DEAD_PALM_SAPLING (TREE_PALM_FRUIT + 1)
/* cedar tree */
#define CEDAR_TREE_SAPLING (DEAD_PALM_SAPLING + 1)
#define CEDAR_TREE_S0 (CEDAR_TREE_SAPLING + 1)
#define CEDAR_TREE_S1 (CEDAR_TREE_S0 + 1)
#define CEDAR_TREE_S2 (CEDAR_TREE_S1 + 1)
#define CEDAR_TREE (CEDAR_TREE_S2 + 1) /* fully grown */
#define DEAD_CEDAR_SAPLING (CEDAR_TREE + 1)
/* gold tree */
#define GOLD_TREE_SAPLING (DEAD_CEDAR_SAPLING + 1)
#define GOLD_TREE_S0 (GOLD_TREE_SAPLING + 1)
#define GOLD_TREE_S1 (GOLD_TREE_S0 + 1)
#define GOLD_TREE_S2 (GOLD_TREE_S1 + 1)
#define GOLD_TREE_SHOVEL (GOLD_TREE_S2 + 1) /* fully grown w/ golden shovel */
#define GOLD_TREE (GOLD_TREE_SHOVEL + 1) /* fully grown */
#define DEAD_GOLD_SAPLING (GOLD_TREE + 1)
/* end of environmental objects */

#define SNOWMAN0 0xA008
#define SNOWMAN1 (SNOWMAN0 + 1)
#define SNOWMAN2 (SNOWMAN1 + 1)
#define SNOWMAN3 (SNOWMAN2 + 1)
#define SNOWMAN4 (SNOWMAN3 + 1)
#define SNOWMAN5 (SNOWMAN4 + 1)
#define SNOWMAN6 (SNOWMAN5 + 1)
#define SNOWMAN7 (SNOWMAN6 + 1)
#define SNOWMAN8 (SNOWMAN7 + 1)

#define SP_NPC_START 0xD000
#define SP_NPC_ARTIST (SP_NPC_START + 0) // D000
#define SP_NPC_BROKER (SP_NPC_START + 1) // D001
#define SP_NPC_DESIGNER (SP_NPC_START + 2) // D002
#define SP_NPC_POST_GIRL (SP_NPC_START + 3) // D003
#define SP_NPC_GUIDE (SP_NPC_START + 4) // D004
#define SP_NPC_GUIDE2 (SP_NPC_START + 5) // D005
#define SP_NPC_CARPETPEDDLER (SP_NPC_START + 6) // D006
#define SP_NPC_KABUPEDDLER (SP_NPC_START + 7) // D007
#define SP_NPC_SHOP_MASTER (SP_NPC_START + 8) // D008
#define SP_NPC_CONV_MASTER (SP_NPC_START + 9) // D009
#define SP_NPC_SUPER_MASTER (SP_NPC_START + 10) // D00A
#define SP_NPC_DEPART_MASTER (SP_NPC_START + 11) // D00B
#define SP_NPC_GYPSY (SP_NPC_START + 12) // D00C
#define SP_NPC_POLICE (SP_NPC_START + 13) // D00D
#define SP_NPC_STATION_MASTER (SP_NPC_START + 14) // D00E
#define SP_NPC_SANTA (SP_NPC_START + 15) // D00F
#define SP_NPC_POLICE2 (SP_NPC_START + 16) // D010
#define SP_NPC_POST_MAN (SP_NPC_START + 17) // D011
#define SP_NPC_POST_GIRL2 (SP_NPC_START + 18) // D012
#define SP_NPC_EV_BROKER2 (SP_NPC_START + 19) // D013
#define SP_NPC_RCN_GUIDE (SP_NPC_START + 20) // D014
#define SP_NPC_RCN_GUIDE_1 (SP_NPC_START + 21) // D015
#define SP_NPC_RCN_GUIDE_2 (SP_NPC_START + 22) // D016
#define SP_NPC_RCN_GUIDE_3 (SP_NPC_START + 23) // D017
#define SP_NPC_P_SEL (SP_NPC_START + 24) // D018
#define SP_NPC_RCN_GUIDE2 (SP_NPC_START + 25) // D019
#define SP_NPC_RCN_GUIDE2_1 (SP_NPC_START + 26) // D01A
#define SP_NPC_RCN_GUIDE2_2 (SP_NPC_START + 27) // D01B
#define SP_NPC_RCN_GUIDE2_3 (SP_NPC_START + 28) // D01C
#define SP_NPC_ANGLER (SP_NPC_START + 29) // D01D
#define SP_NPC_SHOP_MASTERSP (SP_NPC_START + 30) // D01E
#define SP_NPC_P_SEL2 (SP_NPC_START + 31) // D01F
#define SP_NPC_EV_HALLOWEEN_0 (SP_NPC_START + 32) // D020
#define SP_NPC_EV_HALLOWEEN_1 (SP_NPC_START + 33) // D021
#define SP_NPC_EV_HALLOWEEN_2 (SP_NPC_START + 34) // D022
#define SP_NPC_EV_HALLOWEEN_3 (SP_NPC_START + 35) // D023
#define SP_NPC_EV_HALLOWEEN_4 (SP_NPC_START + 36) // D024
#define SP_NPC_HALLOWEEN (SP_NPC_START + 37) // D025
#define SP_NPC_MAMEDANUKI0 (SP_NPC_START + 38) // D026
#define SP_NPC_EV_HANABI_0 (SP_NPC_START + 39) // D027
#define SP_NPC_EV_HANABI_1 (SP_NPC_START + 40) // D028
#define SP_NPC_EV_HANABI_2 (SP_NPC_START + 41) // D029
#define SP_NPC_EV_HANABI_3 (SP_NPC_START + 42) // D02A
#define SP_NPC_EV_HANABI_4 (SP_NPC_START + 43) // D02B
#define SP_NPC_EV_YOMISE (SP_NPC_START + 44) // D02C
#define SP_NPC_EV_TOKYOSO_0 (SP_NPC_START + 45) // D02D
#define SP_NPC_EV_TOKYOSO_1 (SP_NPC_START + 46) // D02E
#define SP_NPC_EV_TOKYOSO_2 (SP_NPC_START + 47) // D02F
#define SP_NPC_EV_TOKYOSO_3 (SP_NPC_START + 48) // D030
#define SP_NPC_EV_TOKYOSO_4 (SP_NPC_START + 49) // D031
#define SP_NPC_EV_HANAMI_0 (SP_NPC_START + 50) // D032
#define SP_NPC_EV_HANAMI_1 (SP_NPC_START + 51) // D033
#define SP_NPC_EV_HANAMI_2 (SP_NPC_START + 52) // D034
#define SP_NPC_EV_HANAMI_3 (SP_NPC_START + 53) // D035
#define SP_NPC_EV_HANAMI_4 (SP_NPC_START + 54) // D036
#define SP_NPC_MAMEDANUKI1 (SP_NPC_START + 55) // D037
#define SP_NPC_SLEEP_OBABA (SP_NPC_START + 56) // D038
#define SP_NPC_EV_YOMISE2 (SP_NPC_START + 57) // D039
#define SP_NPC_SHOP_MASTERSP_2 (SP_NPC_START + 58) // D03A
#define SP_NPC_SHOP_MASTERSP_3 (SP_NPC_START + 59) // D03B
#define SP_NPC_SHOP_MASTERSP_4 (SP_NPC_START + 60) // D03C
#define SP_NPC_EV_MIKO (SP_NPC_START + 61) // D03D
#define SP_NPC_MAJIN (SP_NPC_START + 62) // D03E
#define SP_NPC_EV_TUKIMI_0 (SP_NPC_START + 63) // D03F
#define SP_NPC_EV_TUKIMI_1 (SP_NPC_START + 64) // D040
#define SP_NPC_EV_TUKIMI_2 (SP_NPC_START + 65) // D041
#define SP_NPC_EV_TUKIMI_3 (SP_NPC_START + 66) // D042
#define SP_NPC_EV_TUKIMI_4 (SP_NPC_START + 67) // D043
#define SP_NPC_EV_COUNTDOWN_0 (SP_NPC_START + 68) // D044
#define SP_NPC_EV_COUNTDOWN_1 (SP_NPC_START + 69) // D045
#define SP_NPC_EV_COUNTDOWN_2 (SP_NPC_START + 70) // D046
#define SP_NPC_EV_COUNTDOWN_3 (SP_NPC_START + 71) // D047
#define SP_NPC_EV_COUNTDOWN_4 (SP_NPC_START + 72) // D048
#define SP_NPC_EV_TURI_0 (SP_NPC_START + 73) // D049
#define SP_NPC_EV_TURI_1 (SP_NPC_START + 74) // D04A
#define SP_NPC_EV_TURI_2 (SP_NPC_START + 75) // D04B
#define SP_NPC_EV_TURI_3 (SP_NPC_START + 76) // D04C
#define SP_NPC_EV_TURI_4 (SP_NPC_START + 77) // D04D
#define SP_NPC_EV_TAISOU_0 (SP_NPC_START + 78) // D04E
#define SP_NPC_EV_TAISOU_1 (SP_NPC_START + 79) // D04F
#define SP_NPC_EV_TAISOU_2 (SP_NPC_START + 80) // D050
#define SP_NPC_EV_TAISOU_3 (SP_NPC_START + 81) // D051
#define SP_NPC_EV_TAISOU_4 (SP_NPC_START + 82) // D052
#define SP_NPC_EV_TAMAIRE_0 (SP_NPC_START + 83) // D053
#define SP_NPC_EV_TAMAIRE_1 (SP_NPC_START + 84) // D054
#define SP_NPC_EV_TAMAIRE_2 (SP_NPC_START + 85) // D055
#define SP_NPC_EV_TAMAIRE_3 (SP_NPC_START + 86) // D056
#define SP_NPC_EV_TAMAIRE_4 (SP_NPC_START + 87) // D057
#define SP_NPC_EV_HATUMODE_0 (SP_NPC_START + 88) // D058
#define SP_NPC_EV_HATUMODE_1 (SP_NPC_START + 89) // D059
#define SP_NPC_EV_HATUMODE_2 (SP_NPC_START + 90) // D05A
#define SP_NPC_EV_HATUMODE_3 (SP_NPC_START + 91) // D05B
#define SP_NPC_EV_HATUMODE_4 (SP_NPC_START + 92) // D05C
#define SP_NPC_TOTAKEKE (SP_NPC_START + 93) // D05D
#define SP_NPC_EV_KAMAKURA_0 (SP_NPC_START + 94) // D05E
#define SP_NPC_EV_TUNAHIKI_0 (SP_NPC_START + 95) // D05F
#define SP_NPC_EV_TUNAHIKI_1 (SP_NPC_START + 96) // D060
#define SP_NPC_EV_TUNAHIKI_2 (SP_NPC_START + 97) // D061
#define SP_NPC_EV_TUNAHIKI_3 (SP_NPC_START + 98) // D062
#define SP_NPC_EV_TUNAHIKI_4 (SP_NPC_START + 99) // D063
#define SP_NPC_EV_DOZAEMON (SP_NPC_START + 100) // D064
#define SP_NPC_MAJIN2 (SP_NPC_START + 101) // D065
#define SP_NPC_RTC (SP_NPC_START + 102) // D066
#define SP_NPC_ENGINEER (SP_NPC_START + 103) // D067
#define SP_NPC_MAJIN3 (SP_NPC_START + 104) // D068
#define SP_NPC_MAJIN4 (SP_NPC_START + 105) // D069
#define SP_NPC_RESTART (SP_NPC_START + 106) // D06A
#define SP_NPC_MAJIN5 (SP_NPC_START + 107) // D06B
#define SP_NPC_EV_DOKUTU (SP_NPC_START + 108) // D06C
#define SP_NPC_CURATOR (SP_NPC_START + 109) // D06D
#define SP_NPC_EV_SONCHO (SP_NPC_START + 110) // D06E
#define SP_NPC_EV_GHOST (SP_NPC_START + 111) // D06F
#define SP_NPC_NEEDLEWORK0 (SP_NPC_START + 112) // D070
#define SP_NPC_NEEDLEWORK1 (SP_NPC_START + 113) // D071
#define SP_NPC_SENDO (SP_NPC_START + 114) // D072
//
#define SP_NPC_EV_SONCHO2 (SP_NPC_START + 116) // D074
#define SP_NPC_MASK_CAT (SP_NPC_START + 117) // D075
#define SP_NPC_MASK_CAT2 (SP_NPC_START + 118) // D076
//
#define SP_NPC_SONCHO_D078 (SP_NPC_START + 120) // D078
#define SP_NPC_SONCHO_D079 (SP_NPC_START + 121) // D079
#define SP_NPC_SASHO (SP_NPC_START + 122) // D07A
#define SP_NPC_CASTAWAY (SP_NPC_START + 123) // D07B
#define SP_NPC_MAJIN_D07C (SP_NPC_START + 124) // D07C
#define SP_NPC_MAJIN_D07D (SP_NPC_START + 125) // D07D
#define SP_NPC_MAJIN_BROTHER (SP_NPC_START + 126) // D07E
#define SP_NPC_SONCHO (SP_NPC_START + 127) // D07F
#define SP_NPC_MAJIN_D080 (SP_NPC_START + 128) // D080
#define SP_NPC_EV_MAJIN (SP_NPC_START + 129) // D081
#define SP_NPC_EV_HARVEST_0 (SP_NPC_START + 130) // D082
#define SP_NPC_EV_HARVEST_1 (SP_NPC_START + 131) // D083
#define SP_NPC_EV_HARVEST_2 (SP_NPC_START + 132) // D084
#define SP_NPC_EV_HARVEST_3 (SP_NPC_START + 133) // D085
#define SP_NPC_EV_HARVEST_4 (SP_NPC_START + 134) // D086
#define SP_NPC_EV_SPEECH_SONCHO (SP_NPC_START + 135) // D087
#define SP_NPC_EV_GROUNDHOG_0 (SP_NPC_START + 136) // D088
#define SP_NPC_EV_GROUNDHOG_1 (SP_NPC_START + 137) // D089
#define SP_NPC_EV_GROUNDHOG_2 (SP_NPC_START + 138) // D08A
#define SP_NPC_EV_GROUNDHOG_3 (SP_NPC_START + 139) // D08B
#define SP_NPC_EV_GROUNDHOG_4 (SP_NPC_START + 140) // D08C
#define SP_NPC_TURKEY (SP_NPC_START + 141) // D08D
#define SP_NPC_HEM (SP_NPC_START + 142) // D08E
#define SP_NPC_EV_SUMMERCAMP_0 (SP_NPC_START + 143) // 0xD08F

#endif
